name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t your-dockerhub-jafarSw/nginx-static-website:latest .
          docker tag your-dockerhub-jafarSw/nginx-static-website:latest your-dockerhub-jafarSw/nginx-static-website:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push your-dockerhub-jafarSw/nginx-static-website:latest
          docker push your-dockerhub-jafarSw/nginx-static-website:${{ github.sha }}
